version: "3.8"

services:
  test_runner:
    build: .
    image: pytest_runner
    container_name: pytest_runner_container
    volumes:
      - .:/tests_project/  # Mount project directory
      - ./test_results:/tests_project/test_results  # Mount for test results
    command: ["/opt/venv/bin/python", "-m", "pytest", "-s", "--alluredir=test_results/", "/tests_project/tests/"]
